import logging
import time # Added for timestamp in ChatCompletionResponse
from typing import List, Optional, Dict, Any, Union, AsyncGenerator # Added AsyncGenerator
from fastapi import APIRouter, Depends, HTTPException, Body, UploadFile, File
from fastapi.responses import StreamingResponse # Added for TTS
from pydantic import BaseModel, Field, HttpUrl

import httpx # Added for making HTTP requests (still needed for error types)
from ..utils.llm_registry_service import get_llm_registry_service, LLMRegistryService

# Imports for Tool Calling API Endpoints
from ..services.tool_calling.tool_schema_manager import ToolSchemaManager
from ..services.tool_calling.tool_call_state_store import ToolCallStateStore
from ..services.tool_calling.validation_service import ValidationService
from ..services.tool_calling.argument_accumulator_service import ArgumentAccumulatorService
from ..models.tool_calling_models import InitiateToolCallRequest, SubmitArgumentChunkRequest
import asyncio # For starting cleanup worker

logger = logging.getLogger(__name__)
router = APIRouter()

# --- Service Instantiation and Dependency Injection for Tool Calling ---

_tool_schema_manager_instance = ToolSchemaManager()
_validation_service_instance = ValidationService()
_tool_call_state_store_instance = ToolCallStateStore()

_argument_accumulator_service_instance = ArgumentAccumulatorService(
    state_store=_tool_call_state_store_instance,
    schema_manager=_tool_schema_manager_instance,
    validation_service=_validation_service_instance
)

# Dependency provider functions
def get_tool_schema_manager() -> ToolSchemaManager:
    return _tool_schema_manager_instance

def get_validation_service() -> ValidationService:
    return _validation_service_instance

async def get_tool_call_state_store() -> ToolCallStateStore:
    # Ensure cleanup worker is started (idempotently)
    # The ToolCallStateStore's start_cleanup_worker method is designed to be idempotent.
    if not _tool_call_state_store_instance._cleanup_task or _tool_call_state_store_instance._cleanup_task.done():
        await _tool_call_state_store_instance.start_cleanup_worker()
        logger.info("ToolCallStateStore cleanup worker ensured running via dependency.")
    return _tool_call_state_store_instance

async def get_argument_accumulator_service() -> ArgumentAccumulatorService:
    # Ensure store is ready (which in turn ensures its worker is running)
    await get_tool_call_state_store() 
    return _argument_accumulator_service_instance

# --- Pydantic Models for LLM Capabilities ---

# Pydantic Models for Tool Calling (simplified for now)
class Function(BaseModel):
    name: str
    description: Optional[str] = None
    parameters: Optional[Dict[str, Any]] = None

class Tool(BaseModel):
    type: str # e.g., "function"
    function: Function

class FunctionCall(BaseModel):
    name: str
    arguments: str # JSON string

class ToolCall(BaseModel):
    id: str
    type: str # e.g., "function"
    function: FunctionCall

# --- Pydantic Models for Chat Message Content ---

class ChatMessageContentPartText(BaseModel):
    type: str = "text"
    text: str

class ChatMessageContentPartImageURL(BaseModel):
    type: str = "image_url"
    image_url: Union[HttpUrl, str] # str for base64 data URI

class ChatMessageContentPartFile(BaseModel):
    type: str = "file"
    file: Dict[str, Any] # Structure depends on provider, e.g., {"file_id": "...", "format": "..."}

# --- Pydantic Models for Chat ---

class ChatMessage(BaseModel):
    role: str = Field(..., description="The role of the message sender (e.g., 'user', 'assistant', 'system').")
    content: Optional[Union[str, List[Union[ChatMessageContentPartText, ChatMessageContentPartImageURL, ChatMessageContentPartFile]]]] = Field(None, description="The content of the message. Can be a string or a list of content parts (text, image_url, file).")
    tool_calls: Optional[List[ToolCall]] = Field(None, description="Tool calls generated by the model (for assistant messages).")

class ChatCompletionRequest(BaseModel):
    model_alias: str = Field(..., description="The alias of the model to use (e.g., 'openai-chat', 'groq-llama3').")
    messages: List[ChatMessage] = Field(..., description="A list of messages comprising the conversation so far.")
    temperature: Optional[float] = Field(0.7, ge=0.0, le=2.0, description="Sampling temperature.")
    max_tokens: Optional[int] = Field(None, ge=1, description="Maximum number of tokens to generate.")
    stream: Optional[bool] = Field(False, description="Whether to stream the response.")
    user: Optional[str] = Field(None, description="A unique identifier representing your end-user, which can help OpenAI to monitor and detect abuse.")
    tools: Optional[List[Tool]] = Field(None, description="A list of tools the model may call.")
    tool_choice: Optional[Union[str, Dict[str, Any]]] = Field(None, description="Controls which (if any) tool is called by the model.")
    safety_settings: Optional[List[Dict[str, Any]]] = Field(None, description="Safety settings for the model (e.g., Gemini).")
    thinking: Optional[Dict[str, Any]] = Field(None, description="Thinking parameters for the model (e.g., Gemini, Anthropic).")
    reasoning_effort: Optional[str] = Field(None, description="Reasoning effort for the model (e.g., Gemini, Anthropic).")
    cache_control: Optional[Dict[str, Any]] = Field(None, description="Cache control settings for the model (e.g., Gemini, Anthropic).")
    extra_body: Optional[Dict[str, Any]] = Field(None, description="Additional provider-specific parameters.")
    # Add response_format for JSON schema later

class ChatCompletionResponseChoice(BaseModel):
    index: int
    message: ChatMessage
    finish_reason: Optional[str] = None
    # Add logprobs if needed

class ChatCompletionUsage(BaseModel):
    prompt_tokens: int
    completion_tokens: Optional[int] = None
    total_tokens: int

class ChatCompletionResponse(BaseModel):
    id: str
    object: str = "chat.completion"
    created: int
    model: str # This will be the actual model string used by LiteLLM, not the alias
    choices: List[ChatCompletionResponseChoice]
    usage: Optional[ChatCompletionUsage] = None
    # system_fingerprint: Optional[str] = None # LiteLLM might add this

# --- Pydantic Models for Embeddings ---

class EmbeddingRequest(BaseModel):
    model_alias: str = Field(..., description="The alias of the embedding model to use (e.g., 'openai-embedding').")
    input: Union[str, List[str]] = Field(..., description="Input text or list of texts to embed.")
    # encoding_format: Optional[str] = Field("float", description="The format to return the embeddings in. Can be float or base64.") # LiteLLM might support this
    # user: Optional[str] = Field(None, description="A unique identifier representing your end-user.") # LiteLLM might support this

class EmbeddingData(BaseModel):
    object: str = "embedding"
    embedding: List[float]
    index: int

class EmbeddingUsage(BaseModel):
    prompt_tokens: int
    total_tokens: int

class EmbeddingResponse(BaseModel):
    object: str = "list"
    data: List[EmbeddingData]
    model: str # Actual model string used by LiteLLM
    usage: EmbeddingUsage
    # id: Optional[str] = None # LiteLLM might add this

# --- Pydantic Models for Image Generation ---

class ImageGenerationRequest(BaseModel):
    model_alias: str = Field(..., description="The alias of the image generation model to use (e.g., 'openai-dalle3').")
    prompt: str = Field(..., description="A text description of the desired image(s).")
    n: Optional[int] = Field(1, ge=1, le=10, description="The number of images to generate.") # Max value depends on provider
    size: Optional[str] = Field(None, description="The size of the generated images (e.g., '1024x1024', '1792x1024').") # Specific to DALL-E
    quality: Optional[str] = Field(None, description="The quality of the image that will be generated (e.g., 'standard', 'hd').") # Specific to DALL-E
    style: Optional[str] = Field(None, description="The style of the generated images (e.g., 'vivid', 'natural').") # Specific to DALL-E
    response_format: Optional[str] = Field("url", description="The format in which the generated images are returned (e.g., 'url', 'b64_json').")
    # user: Optional[str] = Field(None, description="A unique identifier representing your end-user.")

class ImageGenerationData(BaseModel):
    b64_json: Optional[str] = None
    url: Optional[str] = None
    revised_prompt: Optional[str] = None # DALL-E might revise prompts

class ImageGenerationResponse(BaseModel):
    created: int
    data: List[ImageGenerationData]
    # model: Optional[str] = None # LiteLLM might add this or it's part of the request

# --- Pydantic Models for Text Completion (Legacy, but some models support it) ---

class TextCompletionRequest(BaseModel):
    model_alias: str = Field(..., description="The alias of the model to use (e.g., 'openai-text-davinci-003').")
    prompt: Union[str, List[str]] = Field(..., description="The prompt(s) to generate completions for.")
    max_tokens: Optional[int] = Field(16, ge=1, description="Maximum number of tokens to generate.")
    temperature: Optional[float] = Field(0.7, ge=0.0, le=2.0, description="Sampling temperature.")
    # Add other common parameters like top_p, suffix, logprobs, echo, stop, presence_penalty, frequency_penalty, best_of, logit_bias, user
    stream: Optional[bool] = Field(False, description="Whether to stream the response.")
    user: Optional[str] = Field(None, description="A unique identifier representing your end-user.")

class TextCompletionChoice(BaseModel):
    text: str
    index: int
    logprobs: Optional[Dict[str, Any]] = None # Or a more specific model
    finish_reason: Optional[str] = None

class TextCompletionResponse(BaseModel):
    id: str
    object: str = "text_completion"
    created: int
    model: str # Actual model string used by LiteLLM
    choices: List[TextCompletionChoice]
    usage: Optional[ChatCompletionUsage] = None # Re-use ChatCompletionUsage as it's similar

# --- Pydantic Models for Audio Transcription ---

class AudioTranscriptionRequest(BaseModel): # This will be part of a multipart form, not JSON body
    model_alias: str = Field(..., description="The alias of the audio transcription model.")
    # file: UploadFile # This will be handled by FastAPI's File parameter directly
    language: Optional[str] = Field(None, description="The language of the input audio (ISO 639-1 format).")
    prompt: Optional[str] = Field(None, description="An optional text to guide the model's style or continue a previous audio segment.")
    response_format: Optional[str] = Field("json", description="Format of the transcript output (e.g., 'json', 'text', 'srt', 'verbose_json', 'vtt').")
    temperature: Optional[float] = Field(0.0, ge=0.0, le=1.0, description="Sampling temperature for transcription.")
    # timestamp_granularities: Optional[List[str]] = Field(None, description="Granularity of timestamps (e.g., ['segment', 'word']). OpenAI specific.")


class AudioTranscriptionResponse(BaseModel):
    text: str # The transcribed text.
    # For verbose_json, the structure is more complex, this model might need to adapt or return raw dict
    # For simplicity, assuming 'text' format or 'json' that primarily returns text.
    language: Optional[str] = None # Detected language
    duration: Optional[float] = None # Duration of the audio
    segments: Optional[List[Dict[str, Any]]] = None # For verbose_json
    words: Optional[List[Dict[str, Any]]] = None # For verbose_json with word timestamps


# --- Pydantic Models for Text-to-Speech ---

class TextToSpeechRequest(BaseModel):
    model_alias: str = Field(..., description="The alias of the TTS model to use (e.g., 'openai-tts-1').")
    input: str = Field(..., description="The text to synthesize.")
    voice: str = Field(..., description="The voice to use (e.g., 'alloy', 'echo', 'fable', 'onyx', 'nova', 'shimmer').") # OpenAI specific
    response_format: Optional[str] = Field("mp3", description="The format of the audio output (e.g., 'mp3', 'opus', 'aac', 'flac').") # OpenAI specific
    speed: Optional[float] = Field(1.0, ge=0.25, le=4.0, description="Speed of the generated audio.") # OpenAI specific

# Response for TTS will be the audio file itself, so no specific Pydantic model for the response body here.

# --- Pydantic Models for Vision Analysis ---

class VisionMessageContentPartText(BaseModel):
    type: str = "text"
    text: str

class VisionMessageContentPartImageURL(BaseModel):
    type: str = "image_url"
    image_url: Union[HttpUrl, str] # str for base64 data URI

# VisionMessage is no longer needed as ChatMessage can handle vision content
# class VisionMessage(BaseModel):
#     role: str = Field(..., description="The role of the message sender (e.g., 'user').")
#     content: List[Union[VisionMessageContentPartText, VisionMessageContentPartImageURL]]

class VisionAnalysisRequest(BaseModel):
    model_alias: str = Field(..., description="The alias of the vision model to use (e.g., 'openai-gpt-4-vision').")
    messages: List[ChatMessage] = Field(..., description="A list of messages, including image URLs, base64 data, file references, and text prompts.") # Changed VisionMessage to ChatMessage
    max_tokens: Optional[int] = Field(300, ge=1, description="Maximum number of tokens to generate in the completion.")
    temperature: Optional[float] = Field(None, ge=0.0, le=2.0, description="Sampling temperature.")
    # user: Optional[str] = Field(None, description="A unique identifier representing your end-user.")

# VisionAnalysisResponse can reuse ChatCompletionResponse structure as output is similar
# For simplicity, we'll assume the response structure is close enough to ChatCompletionResponse.
# If specific fields are different, a dedicated VisionAnalysisResponse model would be needed.
# For now, the /llm/vision-analyze endpoint will use ChatCompletionResponse as its response_model.


@router.get("/llm/status")
async def get_llm_status():
    """
    Basic endpoint to check the status of the LLM routes.
    """
    return {"status": "LLM routes are active"}

@router.get("/models", response_model=List[Dict[str, Any]], tags=["LLM Endpoints", "LLM Registry"])
async def get_registered_models(
    llm_registry: LLMRegistryService = Depends(get_llm_registry_service)
):
    """
    Get the list of available (registered and cached) LLM models.
    Each model entry is a dictionary conforming to the StandardizedLLM Pydantic model.
    """
    try:
        models = llm_registry.get_available_models()
        if not models:
            # This case might occur if the cache is empty and fetch failed,
            # or if no models are genuinely available from the proxy.
            logger.info("No models currently available in the LLM registry.")
            # Return empty list, or could raise HTTPException 404 if preferred.
            # For a model list, an empty list is often a valid response.
            return []
        return [model.model_dump() for model in models] # Convert each model to a dict
    except Exception as e:
        logger.error(f"Error retrieving models from LLMRegistryService: {e}", exc_info=True)
        raise HTTPException(status_code=500, detail="Failed to retrieve LLM models from the registry.")

@router.post("/llm/chat", response_model=ChatCompletionResponse, tags=["LLM Endpoints"])
async def chat_completions(
    request_body: ChatCompletionRequest,
    llm_registry: LLMRegistryService = Depends(get_llm_registry_service)
):
    """
    Endpoint for generating chat completions using a registered LLM.
    """
    try:
        logger.info(f"Received chat completion request for model_alias: {request_body.model_alias}")

        # Convert Pydantic messages with potentially multimodal content to list of dicts for LiteLLM
        messages_for_litellm = []
        for msg in request_body.messages:
            litellm_content = None
            if isinstance(msg.content, str):
                litellm_content = msg.content
            elif isinstance(msg.content, list):
                litellm_content_parts = []
                for part in msg.content:
                    if isinstance(part, ChatMessageContentPartText):
                        litellm_content_parts.append({"type": "text", "text": part.text})
                    elif isinstance(part, ChatMessageContentPartImageURL):
                        # Ensure image_url is passed as a dictionary for LiteLLM
                        litellm_content_parts.append({"type": "image_url", "image_url": {"url": str(part.image_url)}})
                    elif isinstance(part, ChatMessageContentPartFile):
                         # File content part - structure depends on provider, pass as is for now
                         litellm_content_parts.append({"type": "file", "file": part.file})
                litellm_content = litellm_content_parts

            messages_for_litellm.append({
                "role": msg.role,
                "content": litellm_content,
                "tool_calls": [tc.model_dump() for tc in msg.tool_calls] if msg.tool_calls else None # Include tool calls from assistant messages
            })


        # Call the registry service method for chat completion
        # This method should internally handle calling LiteLLM
        # The llm_registry.generate_chat_completion should return a LiteLLM-like response object
        # or a dictionary that can be mapped to ChatCompletionResponse.

        # Construct the payload for the LiteLLM proxy's /v1/chat/completions endpoint
        # This payload should match the OpenAI Chat Completion API format, which LiteLLM supports.
        litellm_payload = {
            "model": request_body.model_alias, # Use the alias as the model name for the proxy
            "messages": messages_for_litellm,
            "temperature": request_body.temperature,
            "max_tokens": request_body.max_tokens,
            "stream": request_body.stream,
            "user": request_body.user,
            "tools": [tool.model_dump(exclude_none=True) for tool in request_body.tools] if request_body.tools else None, # Convert Pydantic models to dicts
            "tool_choice": request_body.tool_choice,
            "safety_settings": request_body.safety_settings,
            "thinking": request_body.thinking,
            "reasoning_effort": request_body.reasoning_effort,
            "cache_control": request_body.cache_control,
            "extra_body": request_body.extra_body,
            # Add response_format for JSON schema later
        }
        
        # Remove None values from the payload to avoid sending nulls for optional fields
        litellm_payload = {k: v for k, v in litellm_payload.items() if v is not None}

        # Process tools for the service call
        tools_for_litellm = [tool.model_dump(exclude_none=True) for tool in request_body.tools] if request_body.tools else None

        logger.info(f"Calling chat_completion_advanced service for model_alias: {request_body.model_alias}")

        service_response = await llm_registry.chat_completion_advanced(
            model_alias=request_body.model_alias,
            messages=messages_for_litellm,
            temperature=request_body.temperature,
            max_tokens=request_body.max_tokens,
            stream=request_body.stream,
            user=request_body.user,
            tools=tools_for_litellm,
            tool_choice=request_body.tool_choice,
            safety_settings=request_body.safety_settings,
            thinking=request_body.thinking,
            reasoning_effort=request_body.reasoning_effort,
            cache_control=request_body.cache_control,
            extra_body=request_body.extra_body
            # request_timeout is not explicitly passed here, using service default
        )

        if request_body.stream:
            # service_response is an AsyncGenerator
            return StreamingResponse(service_response, media_type="text/event-stream")
        else:
            # service_response is a Dict
            # Ensure the 'model' field in the response is the actual model used by LiteLLM,
            # as the service might get this from LiteLLM's response.
            # If not present in service_response, use the requested alias (though it should be there).
            actual_model_used = service_response.get("model", request_body.model_alias)
            service_response['model'] = actual_model_used

            # The service_response should be directly usable by ChatCompletionResponse
            # if it matches the OpenAI/LiteLLM format.
            return ChatCompletionResponse(**service_response)

    except httpx.HTTPStatusError as e:
        logger.error(f"HTTP error from LLM service during chat completion ({e.request.url}): {e.response.status_code} - {e.response.text}", exc_info=True)
        error_detail = f"LLM service returned an HTTP error: {e.response.status_code}"
        try:
            error_response_data = e.response.json()
            if "error" in error_response_data and isinstance(error_response_data["error"], dict):
                 error_detail += f" - {error_response_data['error'].get('message', 'Unknown error from LLM service')}"
            elif "detail" in error_response_data: # Some proxies might use 'detail'
                 error_detail += f" - {error_response_data['detail']}"
            else: # Fallback if error structure is unknown
                 error_detail += f" - {e.response.text[:200]}" # Limit length
        except json.JSONDecodeError: # If the error response itself is not JSON
            error_detail += f" - {e.response.text[:200]}"
        raise HTTPException(status_code=e.response.status_code, detail=error_detail)
    except httpx.RequestError as e:
        logger.error(f"Request error connecting to LLM service during chat completion ({e.request.url}): {e}", exc_info=True)
        raise HTTPException(status_code=503, detail=f"Failed to connect to LLM service: {str(e)}") # 503 Service Unavailable
    except json.JSONDecodeError as e: # If service returns non-JSON for non-streaming, or if ChatCompletionResponse parsing fails
        logger.error(f"JSON decode error processing response from LLM service for chat completion: {e.msg}", exc_info=True)
        raise HTTPException(status_code=500, detail=f"Invalid JSON response from LLM service: {e.msg}")
    except Exception as e: # Catch-all for other unexpected errors
        logger.error(f"Unexpected error during chat completion for model_alias {request_body.model_alias}: {e}", exc_info=True)
        raise HTTPException(status_code=500, detail=f"An unexpected error occurred: {str(e)}")

@router.post("/llm/embeddings", response_model=EmbeddingResponse, tags=["LLM Endpoints"])
async def create_embeddings(
    request_body: EmbeddingRequest,
    llm_registry: LLMRegistryService = Depends(get_llm_registry_service)
):
    """
    Endpoint for generating embeddings for input text(s) using a registered LLM.
    """
    try:
        logger.info(f"Received embedding request for model_alias: {request_body.model_alias}")

        # Construct the payload for the LiteLLM proxy's /v1/embeddings endpoint
        litellm_payload = {
            "model": request_body.model_alias, # Use the alias as the model name for the proxy
            "input": request_body.input,
            # Add other parameters like encoding_format, user if supported and needed
        }
        
        # The EmbeddingRequest model does not currently have an 'extra_body' field.
        # If it were to be added, it could be accessed like:
        # extra_body_payload = getattr(request_body, 'extra_body', None)
        # For now, we pass None as the service method handles it.
        extra_body_payload = None 

        logger.info(f"Calling create_embeddings_advanced service for model_alias: {request_body.model_alias}")

        service_response_dict = await llm_registry.create_embeddings_advanced(
            model_alias=request_body.model_alias,
            input_data=request_body.input,
            extra_body=extra_body_payload
            # request_timeout can be passed if desired, using service default for now
        )

        # The service_response_dict should contain the 'model' field as returned by LiteLLM.
        # EmbeddingResponse Pydantic model will validate this.
        return EmbeddingResponse(**service_response_dict)

    except httpx.HTTPStatusError as e:
        logger.error(f"HTTP error from LLM service during embedding creation ({e.request.url}): {e.response.status_code} - {e.response.text}", exc_info=True)
        error_detail = f"LLM service returned an HTTP error: {e.response.status_code}"
        try:
            error_response_data = e.response.json()
            if "error" in error_response_data and isinstance(error_response_data["error"], dict):
                 error_detail += f" - {error_response_data['error'].get('message', 'Unknown error from LLM service')}"
            elif "detail" in error_response_data:
                 error_detail += f" - {error_response_data['detail']}"
            else:
                 error_detail += f" - {e.response.text[:200]}" # Limit length
        except json.JSONDecodeError:
            error_detail += f" - {e.response.text[:200]}"
        raise HTTPException(status_code=e.response.status_code, detail=error_detail)
    except httpx.RequestError as e:
        logger.error(f"Request error connecting to LLM service during embedding creation ({e.request.url}): {e}", exc_info=True)
        raise HTTPException(status_code=503, detail=f"Failed to connect to LLM service: {str(e)}") # 503 Service Unavailable
    except json.JSONDecodeError as e: # If service returns non-JSON or EmbeddingResponse parsing fails
        logger.error(f"JSON decode error processing response from LLM service for embedding creation: {e.msg}", exc_info=True)
        raise HTTPException(status_code=500, detail=f"Invalid JSON response from LLM service: {e.msg}")
    except Exception as e: # Catch-all for other unexpected errors
        logger.error(f"Unexpected error during embedding creation for model_alias {request_body.model_alias}: {e}", exc_info=True)
        raise HTTPException(status_code=500, detail=f"An unexpected error occurred: {str(e)}")

@router.post("/llm/generate-image", response_model=ImageGenerationResponse, tags=["LLM Endpoints"])
async def create_image_generation(
    request_body: ImageGenerationRequest,
    llm_registry: LLMRegistryService = Depends(get_llm_registry_service)
):
    """
    Endpoint for generating images from text prompts using a registered LLM.
    """
    try:
        logger.info(f"Received image generation request for model_alias: {request_body.model_alias}")

        # ImageGenerationRequest doesn't currently have extra_body.
        # If it needs to support extra_body, it should be added to its Pydantic model.
        extra_body_payload = getattr(request_body, 'extra_body', None)

        logger.info(f"Calling generate_image_advanced service for model_alias: {request_body.model_alias}")

        service_response_dict = await llm_registry.generate_image_advanced(
            model_alias=request_body.model_alias,
            prompt=request_body.prompt,
            n=request_body.n,
            size=request_body.size,
            quality=request_body.quality,
            style=request_body.style,
            response_format=request_body.response_format,
            extra_body=extra_body_payload
            # request_timeout can be passed if desired, using service default for now
        )

        # The service_response_dict should be directly parsable by ImageGenerationResponse.
        # LiteLLM's response for image generation typically includes 'created' and 'data' fields.
        return ImageGenerationResponse(**service_response_dict)

    except httpx.HTTPStatusError as e:
        logger.error(f"HTTP error from LLM service during image generation ({e.request.url}): {e.response.status_code} - {e.response.text}", exc_info=True)
        error_detail = f"LLM service returned an HTTP error: {e.response.status_code}"
        try:
            error_response_data = e.response.json()
            if "error" in error_response_data and isinstance(error_response_data["error"], dict):
                 error_detail += f" - {error_response_data['error'].get('message', 'Unknown error from LLM service')}"
            elif "detail" in error_response_data:
                 error_detail += f" - {error_response_data['detail']}"
            else:
                 error_detail += f" - {e.response.text[:200]}" # Limit length
        except json.JSONDecodeError:
            error_detail += f" - {e.response.text[:200]}"
        raise HTTPException(status_code=e.response.status_code, detail=error_detail)
    except httpx.RequestError as e:
        logger.error(f"Request error connecting to LLM service during image generation ({e.request.url}): {e}", exc_info=True)
        raise HTTPException(status_code=503, detail=f"Failed to connect to LLM service: {str(e)}") # 503 Service Unavailable
    except json.JSONDecodeError as e: # If service returns non-JSON or ImageGenerationResponse parsing fails
        logger.error(f"JSON decode error processing response from LLM service for image generation: {e.msg}", exc_info=True)
        raise HTTPException(status_code=500, detail=f"Invalid JSON response from LLM service: {e.msg}")
    except Exception as e: # Catch-all for other unexpected errors
        logger.error(f"Unexpected error during image generation for model_alias {request_body.model_alias}: {e}", exc_info=True)
        raise HTTPException(status_code=500, detail=f"An unexpected error occurred: {str(e)}")


# The /llm/text-completion endpoint seems to be a new addition not covered by previous refactoring tasks.
# If it was intended to be refactored, it would follow a similar pattern,
# potentially using llm_registry.chat_completion_advanced with a specific prompt structure
# or a new service method llm_registry.text_completion_advanced if the /v1/completions
# endpoint in LiteLLM has significantly different parameters or response structures than chat.
# For now, I will assume this endpoint is either new or intentionally not yet refactored,
# as the task was to clean up after the six specified "advanced" methods.
# If this endpoint also needs refactoring to use a service method, that would be a separate step.

@router.post("/llm/text-completion", response_model=TextCompletionResponse, tags=["LLM Endpoints"])
async def create_text_completion(
    request_body: TextCompletionRequest,
    llm_registry: LLMRegistryService = Depends(get_llm_registry_service)
):
    """
    Endpoint for generating text completions using a registered LLM.
    Note: Many newer models favor chat completions over text completions.
    """
    try:
        logger.info(f"Received text completion request for model_alias: {request_body.model_alias}")

        # Construct the payload for the LiteLLM proxy's /v1/completions endpoint
        litellm_payload = {
            "model": request_body.model_alias, # Use the alias as the model name for the proxy
            "prompt": request_body.prompt,
            "max_tokens": request_body.max_tokens,
            "temperature": request_body.temperature,
            "stream": request_body.stream,
            "user": request_body.user
            # Add other parameters as needed
        }
        
        # Remove None values from the payload
        litellm_payload = {k: v for k, v in litellm_payload.items() if v is not None}

        logger.info(f"Sending text completion request to LiteLLM proxy: {LITELLM_PROXY_URL}/v1/completions")
        
        headers = {}
        if LITELLM_PROXY_API_KEY:
            headers["Authorization"] = f"Bearer {LITELLM_PROXY_API_KEY}"

        async with httpx.AsyncClient(timeout=120.0) as client: # Use httpx to call the proxy
            response = await client.post(
                f"{LITELLM_PROXY_URL}/v1/completions",
                json=litellm_payload,
                headers=headers
            )
            response.raise_for_status() # Raise an exception for bad status codes (4xx or 5xx)
            
            # If streaming, return a StreamingResponse
            if request_body.stream:
                async def stream_response():
                    async for chunk in response.aiter_bytes():
                        yield chunk
                # Determine media type - text/event-stream for SSE
                return StreamingResponse(stream_response(), media_type="text/event-stream")

            # If not streaming, parse the JSON response
            litellm_text_completion_response = response.json()

        # Map LiteLLM's text completion response structure to our TextCompletionResponse Pydantic model.
        # LiteLLM's response should be compatible with OpenAI's CompletionResponse.
        # We can directly use the Pydantic model's parsing capabilities.
        
        # Ensure the 'model' field in the response is the actual model used by LiteLLM
        actual_model_used = litellm_text_completion_response.get("model", request_body.model_alias)
        litellm_text_completion_response['model'] = actual_model_used # Ensure our model uses the actual model ID

        # Use the Pydantic model to parse the response data
        return TextCompletionResponse(**litellm_text_completion_response)

    except httpx.HTTPStatusError as e:
        logger.error(f"HTTP error calling LiteLLM proxy text completion endpoint ({e.request.url}): {e.response.status_code} - {e.response.text}", exc_info=True)
        error_detail = f"LLM proxy returned an HTTP error: {e.response.status_code}"
        try:
            error_response_data = e.response.json()
            if "error" in error_response_data and isinstance(error_response_data["error"], dict):
                 error_detail += f" - {error_response_data['error'].get('message', 'Unknown error from proxy')}"
            elif "detail" in error_response_data:
                 error_detail += f" - {error_response_data['detail']}"
            else:
                 error_detail += f" - {e.response.text}" # Fallback to raw text
        except json.JSONDecodeError:
            error_detail += f" - {e.response.text}" # Fallback to raw text if JSON parsing fails
            
        raise HTTPException(status_code=e.response.status_code, detail=error_detail)
    except httpx.RequestError as e:
        logger.error(f"Request error calling LiteLLM proxy text completion endpoint ({e.request.url}): {e}", exc_info=True)
        raise HTTPException(status_code=500, detail=f"Failed to connect to LLM proxy: {e}")
    except Exception as e:
        logger.error(f"Unexpected error during text completion for model_alias {request_body.model_alias}: {e}", exc_info=True)
        raise HTTPException(status_code=500, detail=f"An unexpected error occurred: {str(e)}")

@router.post("/llm/transcribe-audio", response_model=AudioTranscriptionResponse, tags=["LLM Endpoints"])
async def create_audio_transcription(
    model_alias: str = Body(..., description="The alias of the audio transcription model."),
    language: Optional[str] = Body(None, description="Language of the input audio (ISO 639-1)."),
    prompt: Optional[str] = Body(None, description="Optional text to guide the model."),
    response_format: Optional[str] = Body("json", description="Format of the transcript output."),
    temperature: Optional[float] = Body(0.0, description="Sampling temperature."),
    file: UploadFile = File(..., description="The audio file to transcribe."),
    llm_registry: LLMRegistryService = Depends(get_llm_registry_service)
):
    """
    Endpoint for transcribing audio using a registered LLM.
    Accepts audio file via multipart/form-data.
    """
    try:
        logger.info(f"Received audio transcription request for model_alias: {model_alias}, filename: {file.filename}")

        file_data = await file.read()
        
        # The route currently doesn't explicitly collect 'extra_form_data'.
        # If this is needed, the route signature or logic would have to change
        # to gather additional Body fields into a dict. For now, pass None.
        extra_data_payload = None

        logger.info(f"Calling transcribe_audio_advanced service for model_alias: {model_alias}")

        service_response = await llm_registry.transcribe_audio_advanced(
            model_alias=model_alias,
            file_name=file.filename,
            file_data=file_data,
            content_type=file.content_type,
            language=language,
            prompt=prompt,
            response_format=response_format,
            temperature=temperature,
            extra_form_data=extra_data_payload
            # request_timeout can be passed if desired, using service default for now
        )

        if isinstance(service_response, str):
            # For text, srt, vtt formats, FastAPI will handle Content-Type as text/plain
            return service_response 
        elif isinstance(service_response, dict):
            # For json, verbose_json formats
            return AudioTranscriptionResponse(**service_response)
        else:
            # Should not happen based on service method's return type hint, but good for safety
            logger.error(f"Unexpected response type from LLM service transcription: {type(service_response)}. Expected str or dict.")
            raise HTTPException(status_code=500, detail="Audio transcription failed: Unexpected response format from LLM service.")

    except httpx.HTTPStatusError as e:
        logger.error(f"HTTP error from LLM service during audio transcription ({e.request.url}): {e.response.status_code} - {e.response.text}", exc_info=True)
        error_detail = f"LLM service returned an HTTP error: {e.response.status_code}"
        try:
            error_response_data = e.response.json() # Error response from proxy might be JSON
            if "error" in error_response_data and isinstance(error_response_data["error"], dict):
                 error_detail += f" - {error_response_data['error'].get('message', 'Unknown error from LLM service')}"
            elif "detail" in error_response_data:
                 error_detail += f" - {error_response_data['detail']}"
            else:
                 error_detail += f" - {e.response.text[:200]}" # Limit length
        except json.JSONDecodeError: # If the error response itself is not JSON
            error_detail += f" - {e.response.text[:200]}"
        raise HTTPException(status_code=e.response.status_code, detail=error_detail)
    except httpx.RequestError as e:
        logger.error(f"Request error connecting to LLM service during audio transcription ({e.request.url}): {e}", exc_info=True)
        raise HTTPException(status_code=503, detail=f"Failed to connect to LLM service: {str(e)}") # 503 Service Unavailable
    except json.JSONDecodeError as e: # If service returns JSON but it's malformed for AudioTranscriptionResponse
        logger.error(f"JSON decode error processing response from LLM service for audio transcription: {e.msg}", exc_info=True)
        raise HTTPException(status_code=500, detail=f"Invalid JSON response from LLM service: {e.msg}")
    except Exception as e: # Catch-all for other unexpected errors
        logger.error(f"Unexpected error during audio transcription for model_alias {model_alias}: {e}", exc_info=True)
        raise HTTPException(status_code=500, detail=f"An unexpected error occurred: {str(e)}")
    # No finally block for temp file cleanup needed anymore

@router.post("/llm/text-to-speech", tags=["LLM Endpoints"])
async def create_text_to_speech(
    request_body: TextToSpeechRequest,
    llm_registry: LLMRegistryService = Depends(get_llm_registry_service)
):
    """
    Endpoint for synthesizing speech from text using a registered LLM.
    Streams the audio output.
    """
    try:
        logger.info(f"Received text-to-speech request for model_alias: {request_body.model_alias}, voice: {request_body.voice}")

        # TextToSpeechRequest doesn't currently have extra_body.
        # If it needs to support extra_body, it should be added to its Pydantic model.
        extra_body_payload = getattr(request_body, 'extra_body', None)

        logger.info(f"Calling synthesize_speech_advanced service for model_alias: {request_body.model_alias}")

        audio_stream_generator, media_type = await llm_registry.synthesize_speech_advanced(
            model_alias=request_body.model_alias,
            input_text=request_body.input,
            voice=request_body.voice,
            response_format=request_body.response_format,
            speed=request_body.speed,
            extra_body=extra_body_payload
            # request_timeout can be passed if desired, using service default for now
        )
        
        output_filename = f"speech_{int(time.time())}.{request_body.response_format}"
        return StreamingResponse(
            audio_stream_generator,
            media_type=media_type,
            headers={"Content-Disposition": f"attachment; filename=\"{output_filename}\""}
        )

    except httpx.HTTPStatusError as e:
        logger.error(f"HTTP error from LLM service during text-to-speech ({e.request.url}): {e.response.status_code} - {e.response.text}", exc_info=True)
        error_detail = f"LLM service returned an HTTP error: {e.response.status_code}"
        try:
            # TTS errors might not be JSON, but attempt parsing just in case
            error_response_data = e.response.json()
            if "error" in error_response_data and isinstance(error_response_data["error"], dict):
                 error_detail += f" - {error_response_data['error'].get('message', 'Unknown error from LLM service')}"
            elif "detail" in error_response_data:
                 error_detail += f" - {error_response_data['detail']}"
            else:
                 error_detail += f" - {e.response.text[:200]}" # Limit length
        except json.JSONDecodeError:
            error_detail += f" - {e.response.text[:200]}"
        raise HTTPException(status_code=e.response.status_code, detail=error_detail)
    except httpx.RequestError as e:
        logger.error(f"Request error connecting to LLM service during text-to-speech ({e.request.url}): {e}", exc_info=True)
        raise HTTPException(status_code=503, detail=f"Failed to connect to LLM service: {str(e)}") # 503 Service Unavailable
    except Exception as e: # Catch-all for other unexpected errors
        logger.error(f"Unexpected error during text-to-speech for model_alias {request_body.model_alias}: {e}", exc_info=True)
        raise HTTPException(status_code=500, detail=f"An unexpected error occurred: {str(e)}")

@router.post("/llm/vision-analyze", response_model=ChatCompletionResponse, tags=["LLM Endpoints"]) # Reusing ChatCompletionResponse
async def create_vision_analysis(
    request_body: VisionAnalysisRequest,
    llm_registry: LLMRegistryService = Depends(get_llm_registry_service)
):
    """
    Endpoint for analyzing images using a registered vision-capable LLM.
    """
    try:
        logger.info(f"Received vision analysis request for model_alias: {request_body.model_alias}")

        # Convert Pydantic messages to list of dicts for LiteLLM, handling the content parts
        messages_for_litellm = []
        for msg in request_body.messages: # msg is now ChatMessage
            litellm_content = None
            if isinstance(msg.content, str): # Should ideally be a list for vision, but handle for robustness
                litellm_content = msg.content
            elif isinstance(msg.content, list):
                litellm_content_parts = []
                for part in msg.content:
                    if isinstance(part, ChatMessageContentPartText):
                        litellm_content_parts.append({"type": "text", "text": part.text})
                    elif isinstance(part, ChatMessageContentPartImageURL):
                        litellm_content_parts.append({"type": "image_url", "image_url": {"url": str(part.image_url)}})
                    elif isinstance(part, ChatMessageContentPartFile):
                        # Vision models might support other file types (e.g., PDFs with Gemini)
                        litellm_content_parts.append({"type": "file", "file": part.file})
                litellm_content = litellm_content_parts
            
            messages_for_litellm.append({
                "role": msg.role, 
                "content": litellm_content
                # tool_calls are not typically used in direct vision analysis, but ChatMessage supports it
            })
        
        # VisionAnalysisRequest doesn't currently have extra_body.
        # If it needs to support extra_body, it should be added to its Pydantic model.
        extra_body_payload = getattr(request_body, 'extra_body', None)

        logger.info(f"Calling analyze_vision_advanced service for model_alias: {request_body.model_alias}")
        
        service_response_dict = await llm_registry.analyze_vision_advanced(
            model_alias=request_body.model_alias,
            messages=messages_for_litellm, # Pass the processed messages
            max_tokens=request_body.max_tokens,
            temperature=request_body.temperature,
            extra_body=extra_body_payload
            # request_timeout can be passed if desired, using service default for now
        )

        # The service_response_dict should contain the 'model' field as returned by LiteLLM.
        # ChatCompletionResponse Pydantic model will validate this.
        # Ensure the 'model' field in the response is the actual model used by LiteLLM
        actual_model_used = service_response_dict.get("model", request_body.model_alias)
        service_response_dict['model'] = actual_model_used
        
        return ChatCompletionResponse(**service_response_dict)

    except httpx.HTTPStatusError as e:
        logger.error(f"HTTP error from LLM service during vision analysis ({e.request.url}): {e.response.status_code} - {e.response.text}", exc_info=True)
        error_detail = f"LLM service returned an HTTP error: {e.response.status_code}"
        try:
            error_response_data = e.response.json()
            if "error" in error_response_data and isinstance(error_response_data["error"], dict):
                 error_detail += f" - {error_response_data['error'].get('message', 'Unknown error from LLM service')}"
            elif "detail" in error_response_data:
                 error_detail += f" - {error_response_data['detail']}"
            else:
                 error_detail += f" - {e.response.text[:200]}" # Limit length
        except json.JSONDecodeError:
            error_detail += f" - {e.response.text[:200]}"
        raise HTTPException(status_code=e.response.status_code, detail=error_detail)
    except httpx.RequestError as e:
        logger.error(f"Request error connecting to LLM service during vision analysis ({e.request.url}): {e}", exc_info=True)
        raise HTTPException(status_code=503, detail=f"Failed to connect to LLM service: {str(e)}") # 503 Service Unavailable
    except json.JSONDecodeError as e: # If service returns non-JSON or ChatCompletionResponse parsing fails
        logger.error(f"JSON decode error processing response from LLM service for vision analysis: {e.msg}", exc_info=True)
        raise HTTPException(status_code=500, detail=f"Invalid JSON response from LLM service: {e.msg}")
    except Exception as e: # Catch-all for other unexpected errors
        logger.error(f"Unexpected error during vision analysis for model_alias {request_body.model_alias}: {e}", exc_info=True)
        raise HTTPException(status_code=500, detail=f"An unexpected error occurred: {str(e)}")

# TODO: Add documentation for these endpoints.

# --- Tool Calling API Endpoints ---

@router.post("/tools/initiate", response_model=Dict[str, str], tags=["Tool Calling"])
async def initiate_tool_call_api(
    request: InitiateToolCallRequest,
    accumulator_service: ArgumentAccumulatorService = Depends(get_argument_accumulator_service)
):
    try:
        tool_call_id = await accumulator_service.initiate_tool_call(request)
        return {"tool_call_id": tool_call_id}
    except ValueError as e:
        logger.error(f"Failed to initiate tool call: {e}", exc_info=True)
        raise HTTPException(status_code=400, detail=str(e))
    except Exception as e:
        logger.error(f"Unexpected error initiating tool call: {e}", exc_info=True)
        raise HTTPException(status_code=500, detail="Failed to initiate tool call")

@router.post("/tools/submit_chunk", response_model=Dict[str, str], tags=["Tool Calling"])
async def submit_tool_argument_chunk_api(
    request: SubmitArgumentChunkRequest,
    accumulator_service: ArgumentAccumulatorService = Depends(get_argument_accumulator_service)
):
    try:
        success, message = await accumulator_service.submit_argument_chunk(request)
        if success:
            return {"status": "success", "message": message}
        else:
            # Determine appropriate status code based on message if possible
            status_code = 400 # Default for client error
            if "not found" in (message or "").lower():
                status_code = 404
            elif "terminal state" in (message or "").lower():
                status_code = 409 # Conflict / already done
            logger.warning(f"Failed to submit chunk for {request.tool_call_id}: {message}")
            raise HTTPException(status_code=status_code, detail=message)
    except HTTPException:
        raise # Re-raise HTTPExceptions directly
    except Exception as e:
        logger.error(f"Unexpected error submitting chunk for {request.tool_call_id}: {e}", exc_info=True)
        raise HTTPException(status_code=500, detail=f"Failed to submit argument chunk: {str(e)}")