from fastapi import APIRouter, Depends, HTTPException, Query, Body, Path
from typing import List, Union
from uuid import UUID
import logging
# from datetime import datetime, timezone # timezone might not be needed if DB handles timestamps

# Import Supabase client and dependency function
from supabase import AsyncClient
from ..dependencies import get_client

# Import Pydantic models
from ..models.presets_models import CrawlPresetCreate, CrawlPresetUpdate, CrawlPresetResponse

logger = logging.getLogger(__name__)
router = APIRouter(prefix="/api/presets", tags=["Crawl Presets"])

@router.post("", response_model=CrawlPresetResponse, status_code=201)
async def create_crawl_preset(
    preset_data: CrawlPresetCreate = Body(...),
    supabase: AsyncClient = Depends(get_client)
):
    # The created_by field is now part of CrawlPresetCreate and validated by Pydantic.
    # RLS policies in Supabase will use auth.uid() against this provided created_by.
    # It's assumed the frontend or calling service, if authenticated, passes the correct user ID.

    preset_dict = preset_data.model_dump()
    # preset_id is generated by the database by default (see V7 migration)
    # created_at and updated_at are also handled by the database (DEFAULT NOW())

    try:
        response = await supabase.table("crawl_presets").insert(preset_dict).execute()

        if hasattr(response, "error") and response.error:
            logger.error(f"Error creating preset: {response.error.message if response.error else 'Unknown error'}")
            raise HTTPException(status_code=400, detail=response.error.message if response.error else "Database error during preset creation.")
        if not response.data:
            logger.error("Failed to create preset, no data returned from Supabase.")
            raise HTTPException(status_code=500, detail="Failed to create preset, no data returned.")

        # Ensure the response data can be parsed by CrawlPresetResponse
        # The DB now automatically sets preset_id, created_at, updated_at.
        # created_by is passed in.
        return CrawlPresetResponse(**response.data[0])
    except Exception as e:
        logger.error(f"Unexpected error creating preset: {e}", exc_info=True)
        raise HTTPException(status_code=500, detail=f"An unexpected error occurred: {str(e)}")


@router.get("", response_model=List[CrawlPresetResponse])
async def list_crawl_presets(
    skip: int = Query(0, ge=0),
    limit: int = Query(100, ge=1, le=1000),
    supabase: AsyncClient = Depends(get_client)
):
    try:
        response = await supabase.table("crawl_presets").select("*").offset(skip).limit(limit).execute()
        if hasattr(response, "error") and response.error:
            logger.error(f"Error listing presets: {response.error.message if response.error else 'Unknown error'}")
            raise HTTPException(status_code=500, detail=response.error.message if response.error else "Database error listing presets.")
        return [CrawlPresetResponse(**item) for item in response.data]
    except Exception as e:
        logger.error(f"Unexpected error listing presets: {e}", exc_info=True)
        raise HTTPException(status_code=500, detail=f"An unexpected error occurred: {str(e)}")

@router.get("/{preset_identifier}", response_model=CrawlPresetResponse)
async def get_crawl_preset(
    preset_identifier: Union[UUID, str] = Path(...),
    supabase: AsyncClient = Depends(get_client)
):
    query = supabase.table("crawl_presets").select("*")
    try:
        uuid_val = UUID(str(preset_identifier))
        query = query.eq("preset_id", uuid_val)
    except ValueError:
        query = query.eq("preset_name", str(preset_identifier))

    try:
        response = await query.limit(1).execute() # Ensure only one record is fetched

        if hasattr(response, "error") and response.error:
            logger.error(f"Error getting preset '{preset_identifier}': {response.error.message if response.error else 'Unknown error'}")
            raise HTTPException(status_code=500, detail=response.error.message if response.error else f"Database error retrieving preset '{preset_identifier}'.")
        if not response.data:
            raise HTTPException(status_code=404, detail=f"Preset '{preset_identifier}' not found")
        return CrawlPresetResponse(**response.data[0])
    except HTTPException as e:
        raise e # Re-raise HTTPException directly
    except Exception as e:
        logger.error(f"Unexpected error getting preset '{preset_identifier}': {e}", exc_info=True)
        raise HTTPException(status_code=500, detail=f"An unexpected error occurred: {str(e)}")


@router.put("/{preset_identifier}", response_model=CrawlPresetResponse)
async def update_crawl_preset(
    preset_data: CrawlPresetUpdate = Body(...),
    preset_identifier: Union[UUID, str] = Path(...),
    supabase: AsyncClient = Depends(get_client)
):
    update_dict = preset_data.model_dump(exclude_unset=True)
    if not update_dict:
        raise HTTPException(status_code=400, detail="No fields to update")

    # updated_at is set by DB trigger or DEFAULT NOW()
    # RLS policies handle ownership checks (auth.uid() = created_by).
    # The application does not need to re-verify created_by here.

    query = supabase.table("crawl_presets").update(update_dict)
    try:
        uuid_val = UUID(str(preset_identifier))
        query = query.eq("preset_id", uuid_val)
    except ValueError:
        query = query.eq("preset_name", str(preset_identifier))

    try:
        # Ensure returning the representation to get the updated data
        response = await query.execute() # For supabase-py v2, .execute() is fine, data is returned by default if matched

        if hasattr(response, "error") and response.error:
            logger.error(f"Error updating preset '{preset_identifier}': {response.error.message if response.error else 'Unknown error'}")
            raise HTTPException(status_code=400, detail=response.error.message if response.error else f"Database error updating preset '{preset_identifier}'.")
        if not response.data:
            # This could mean the preset was not found, or RLS prevented the update.
            # Check RLS: "Allow users to update their own presets" (auth.uid() = created_by)
            raise HTTPException(status_code=404, detail=f"Preset '{preset_identifier}' not found or update failed (possibly RLS restriction).")
        return CrawlPresetResponse(**response.data[0])
    except HTTPException as e:
        raise e # Re-raise HTTPException directly
    except Exception as e:
        logger.error(f"Unexpected error updating preset '{preset_identifier}': {e}", exc_info=True)
        raise HTTPException(status_code=500, detail=f"An unexpected error occurred: {str(e)}")


@router.delete("/{preset_identifier}", status_code=204)
async def delete_crawl_preset(
    preset_identifier: Union[UUID, str] = Path(...),
    supabase: AsyncClient = Depends(get_client)
):
    query = supabase.table("crawl_presets").delete()
    try:
        uuid_val = UUID(str(preset_identifier))
        query = query.eq("preset_id", uuid_val)
    except ValueError:
        query = query.eq("preset_name", str(preset_identifier))

    # RLS policies should handle ownership checks.
    try:
        response = await query.execute()

        if hasattr(response, "error") and response.error:
            logger.error(f"Error deleting preset '{preset_identifier}': {response.error.message if response.error else 'Unknown error'}")
            raise HTTPException(status_code=500, detail=response.error.message if response.error else f"Database error deleting preset '{preset_identifier}'.")

        # For delete, Supabase v2 .execute() returns a response model with data if rows were deleted.
        # If data is empty and no error, it means no rows matched the filter.
        if not response.data:
            raise HTTPException(status_code=404, detail=f"Preset '{preset_identifier}' not found or RLS prevented deletion.")

        # If deletion was successful (response.data is not empty), return 204 No Content.
        # FastAPI will handle the None response as 204 No Content.
        return None
    except HTTPException as e:
        raise e # Re-raise HTTPException directly
    except Exception as e:
        logger.error(f"Unexpected error deleting preset '{preset_identifier}': {e}", exc_info=True)
        raise HTTPException(status_code=500, detail=f"An unexpected error occurred: {str(e)}")
