#!/usr/bin/env bash
# PMOVES-transcribe-and-fetch Environment Bootstrap
# Copies credentials from parent PMOVES.AI repo for standalone mode

set -euo pipefail

SCRIPT_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
ENV_LOCAL="${SCRIPT_ROOT}/.env.local"

echo "=== PMOVES-transcribe-and-fetch Environment Bootstrap ==="
echo ""

# Possible parent locations (check multiple paths)
PARENT_PATHS=(
    "${SCRIPT_ROOT}/../pmoves/env.shared"
    "${SCRIPT_ROOT}/../../PMOVES.AI/pmoves/env.shared"
    "$HOME/Documents/GitHub/PMOVES.AI/pmoves/env.shared"
    "$HOME/OneDrive/Documents/GitHub/PMOVES.AI/pmoves/env.shared"
    "/c/Users/DARKXSIDE/OneDrive/Documents/GitHub/PMOVES.AI/pmoves/env.shared"
    "/d/POWERFULMOVES/PMOVES.AI/pmoves/env.shared"
)

PARENT_ENV=""
for path in "${PARENT_PATHS[@]}"; do
    if [[ -f "$path" ]]; then
        PARENT_ENV="$path"
        break
    fi
done

if [[ -n "$PARENT_ENV" ]]; then
    echo "Found parent PMOVES.AI environment: $PARENT_ENV"
    echo ""

    # Keys to copy from parent (LLM providers)
    KEYS_TO_COPY=(
        "OPENAI_API_KEY"
        "ANTHROPIC_API_KEY"
        "GROQ_API_KEY"
        "GEMINI_API_KEY"
        "GOOGLE_API_KEY"
        "DEEPSEEK_API_KEY"
        "MISTRAL_API_KEY"
        "PERPLEXITYAI_API_KEY"
        "TOGETHER_AI_API_KEY"
        "COHERE_API_KEY"
        "FIREWORKS_AI_API_KEY"
        "XAI_API_KEY"
        "OPENROUTER_API_KEY"
        "NVIDIA_API_KEY"
        "ELEVENLABS_API_KEY"
        # Supabase
        "SUPABASE_URL"
        "SUPABASE_ANON_KEY"
        "SUPABASE_SERVICE_KEY"
        "SUPABASE_JWT_SECRET"
        # Storage
        "MINIO_USER"
        "MINIO_PASSWORD"
        "MINIO_ACCESS_KEY"
        "MINIO_SECRET_KEY"
        "MEILI_MASTER_KEY"
        # Services
        "OLLAMA_BASE_URL"
        "NEO4J_PASSWORD"
        "NEO4J_URL"
        "NEO4J_USER"
        # Hugging Face
        "HUGGINGFACE_HUB_TOKEN"
        "HF_TOKEN"
    )

    # Create or update .env.local
    if [[ ! -f "$ENV_LOCAL" ]]; then
        echo "# Generated by bootstrap_env.sh" > "$ENV_LOCAL"
        echo "# $(date -Iseconds)" >> "$ENV_LOCAL"
        echo "" >> "$ENV_LOCAL"
        echo "# Deployment Mode" >> "$ENV_LOCAL"
        echo "DOCKED_MODE=false" >> "$ENV_LOCAL"
        echo "DB_BACKEND=sqlite" >> "$ENV_LOCAL"
        echo "" >> "$ENV_LOCAL"
    fi

    echo "Copying credentials to .env.local..."
    for key in "${KEYS_TO_COPY[@]}"; do
        value=$(grep "^${key}=" "$PARENT_ENV" 2>/dev/null | head -1 | cut -d'=' -f2- || true)
        if [[ -n "$value" && "$value" != "" && "$value" != *"your-"* && "$value" != *"placeholder"* ]]; then
            # Remove existing key if present (use temp file for portability)
            grep -v "^${key}=" "$ENV_LOCAL" > "${ENV_LOCAL}.tmp" 2>/dev/null || true
            mv "${ENV_LOCAL}.tmp" "$ENV_LOCAL" 2>/dev/null || touch "$ENV_LOCAL"
            echo "${key}=${value}" >> "$ENV_LOCAL"
            echo "  + ${key}"
        fi
    done

    # Also set NEXT_PUBLIC versions for frontend
    echo ""
    echo "Setting NEXT_PUBLIC_ variants for frontend..."

    # Supabase frontend vars
    supa_url=$(grep "^SUPABASE_URL=" "$ENV_LOCAL" 2>/dev/null | cut -d'=' -f2- || true)
    supa_anon=$(grep "^SUPABASE_ANON_KEY=" "$ENV_LOCAL" 2>/dev/null | cut -d'=' -f2- || true)

    if [[ -n "$supa_url" ]]; then
        grep -v "^NEXT_PUBLIC_SUPABASE_URL=" "$ENV_LOCAL" > "${ENV_LOCAL}.tmp" 2>/dev/null || true
        mv "${ENV_LOCAL}.tmp" "$ENV_LOCAL"
        echo "NEXT_PUBLIC_SUPABASE_URL=${supa_url}" >> "$ENV_LOCAL"
        echo "  + NEXT_PUBLIC_SUPABASE_URL"
    fi

    if [[ -n "$supa_anon" ]]; then
        grep -v "^NEXT_PUBLIC_SUPABASE_ANON_KEY=" "$ENV_LOCAL" > "${ENV_LOCAL}.tmp" 2>/dev/null || true
        mv "${ENV_LOCAL}.tmp" "$ENV_LOCAL"
        echo "NEXT_PUBLIC_SUPABASE_ANON_KEY=${supa_anon}" >> "$ENV_LOCAL"
        echo "  + NEXT_PUBLIC_SUPABASE_ANON_KEY"
    fi
else
    echo "Parent PMOVES.AI environment not found"
    echo "Searched paths:"
    for path in "${PARENT_PATHS[@]}"; do
        echo "  - $path"
    done
    echo ""
    echo "Falling back to .env.example..."

    if [[ -f "${SCRIPT_ROOT}/.env.example" ]]; then
        cp "${SCRIPT_ROOT}/.env.example" "$ENV_LOCAL"
        echo "Copied .env.example to .env.local"
        echo "Please manually add your API keys to .env.local"
    else
        echo "No .env.example found. Please create .env.local manually."
        exit 1
    fi
fi

echo ""
echo "=== Validation ==="

# Source the env file safely
set +u
source "$ENV_LOCAL" 2>/dev/null || true
set -u

# Check for at least one LLM provider key
REQUIRED_KEYS=("OPENAI_API_KEY" "ANTHROPIC_API_KEY" "GROQ_API_KEY")
OPTIONAL_KEYS=("SUPABASE_URL" "OLLAMA_BASE_URL" "GEMINI_API_KEY")

echo "LLM Provider Keys (at least one required):"
LLM_FOUND=0
for key in "${REQUIRED_KEYS[@]}"; do
    val="${!key:-}"
    if [[ -n "$val" && "$val" != *"your-"* && "$val" != *"placeholder"* ]]; then
        echo "  [OK] $key"
        LLM_FOUND=$((LLM_FOUND + 1))
    else
        echo "  [--] $key (not set)"
    fi
done

echo ""
echo "Optional keys:"
for key in "${OPTIONAL_KEYS[@]}"; do
    val="${!key:-}"
    if [[ -n "$val" && "$val" != *"your-"* ]]; then
        echo "  [OK] $key"
    else
        echo "  [--] $key (not set)"
    fi
done

echo ""
if [[ $LLM_FOUND -gt 0 ]]; then
    echo "Environment ready! Run: make up-standalone"
else
    echo "WARNING: No LLM provider keys found - some features will not work"
    echo "Please add at least one of: OPENAI_API_KEY, ANTHROPIC_API_KEY, or GROQ_API_KEY"
fi
