import pytest
from fastapi.testclient import TestClient
from unittest.mock import AsyncMock, MagicMock
import uuid
from datetime import datetime, timezone

from backend.app.main import app # Main FastAPI application
from backend.app.dependencies import get_client # The dependency to override
from backend.app.models.presets_models import CrawlPresetCreate, CrawlPresetUpdate, CrawlPresetResponse

# --- Mock Supabase Client Setup ---

class MockSupabaseResponse:
    def __init__(self, data=None, error=None, count=None):
        self.data = data
        self.error = error
        self.count = count

    # Helper to mimic Pydantic model for error attribute if necessary
    # Supabase client errors might have a 'message' attribute
    def __getattr__(self, name):
        if name == 'message' and self.error and isinstance(self.error, str):
            return self.error
        raise AttributeError(f"'{type(self).__name__}' object has no attribute '{name}'")


@pytest.fixture
def mock_supabase_client_fixture():
    mock_client = MagicMock(name="MockSupabaseClient")
    mock_query_builder = MagicMock(name="MockQueryBuilder")

    mock_client.table.return_value = mock_query_builder
    mock_query_builder.select.return_value = mock_query_builder
    mock_query_builder.insert.return_value = mock_query_builder
    mock_query_builder.update.return_value = mock_query_builder
    mock_query_builder.delete.return_value = mock_query_builder
    mock_query_builder.eq.return_value = mock_query_builder
    mock_query_builder.limit.return_value = mock_query_builder
    mock_query_builder.offset.return_value = mock_query_builder

    # .execute() is an async method
    mock_query_builder.execute = AsyncMock(name="execute")

    return mock_client, mock_query_builder.execute # Return client and the execute mock to control its return value

@pytest.fixture(autouse=True)
def override_supabase_dependency(mock_supabase_client_fixture):
    mock_client, _ = mock_supabase_client_fixture
    app.dependency_overrides[get_client] = lambda: mock_client
    yield
    app.dependency_overrides.clear()

# --- Test Data ---

USER_ID_1 = uuid.uuid4()
USER_ID_2 = uuid.uuid4()

def create_sample_preset_data(user_id, name_suffix=""):
    return {
        "preset_id": uuid.uuid4(),
        "preset_name": f"Test Preset {name_suffix}",
        "description": "A test description",
        "version": 1,
        "crawl_tool": "crawl4ai",
        "strategy_definition": {"strategy": "BFS", "depth": 2},
        "target_capability": "web_research",
        "tags": ["test", "example"],
        "created_by": user_id,
        "created_at": datetime.now(timezone.utc).isoformat(),
        "updated_at": datetime.now(timezone.utc).isoformat(),
    }

# --- Tests ---

def test_create_preset_success(client: TestClient, mock_supabase_client_fixture):
    _, mock_execute = mock_supabase_client_fixture

    preset_to_create_data = create_sample_preset_data(USER_ID_1)
    # What the DB insert call would return (includes DB-set fields like preset_id, created_at, updated_at)
    # For this test, we assume the input `created_by` is used and returned.
    # The `preset_id` is generated by DB, so client doesn't send it.
    # `created_at`, `updated_at` also by DB.

    # Mock the response from supabase.insert().execute()
    # The data returned by Supabase after insert includes the full row
    mock_db_response_data = {
        "preset_id": uuid.uuid4(), # Let's assume DB generates this
        "preset_name": preset_to_create_data["preset_name"],
        "description": preset_to_create_data["description"],
        "version": preset_to_create_data["version"],
        "crawl_tool": preset_to_create_data["crawl_tool"],
        "strategy_definition": preset_to_create_data["strategy_definition"],
        "target_capability": preset_to_create_data["target_capability"],
        "tags": preset_to_create_data["tags"],
        "created_by": str(preset_to_create_data["created_by"]), # Ensure it's string for comparison if needed
        "created_at": datetime.now(timezone.utc).isoformat(),
        "updated_at": datetime.now(timezone.utc).isoformat(),
    }
    mock_execute.return_value = MockSupabaseResponse(data=[mock_db_response_data])

    payload = {
        "preset_name": preset_to_create_data["preset_name"],
        "description": preset_to_create_data["description"],
        "strategy_definition": preset_to_create_data["strategy_definition"],
        "target_capability": preset_to_create_data["target_capability"],
        "tags": preset_to_create_data["tags"],
        "created_by": str(USER_ID_1), # Client sends this
        # version is optional in CrawlPresetCreate, defaults in base model
    }

    response = client.post("/api/presets", json=payload)

    assert response.status_code == 201
    data = response.json()
    assert data["preset_name"] == payload["preset_name"]
    assert data["created_by"] == payload["created_by"]
    assert "preset_id" in data
    mock_execute.assert_called_once()


def test_create_preset_missing_fields(client: TestClient):
    payload = { "description": "Missing name and strategy" } # Missing preset_name, strategy_definition, created_by
    response = client.post("/api/presets", json=payload)
    assert response.status_code == 422 # Unprocessable Entity due to Pydantic validation


def test_create_preset_db_error(client: TestClient, mock_supabase_client_fixture):
    _, mock_execute = mock_supabase_client_fixture
    mock_execute.return_value = MockSupabaseResponse(data=None, error="Simulated DB error on insert")

    payload = {
        "preset_name": "Error Case",
        "strategy_definition": {"type": "fail"},
        "created_by": str(USER_ID_1)
    }
    response = client.post("/api/presets", json=payload)
    assert response.status_code == 400 # As per current error handling
    assert "Simulated DB error on insert" in response.json()["detail"]


def test_list_presets_empty(client: TestClient, mock_supabase_client_fixture):
    _, mock_execute = mock_supabase_client_fixture
    mock_execute.return_value = MockSupabaseResponse(data=[])

    response = client.get("/api/presets")
    assert response.status_code == 200
    assert response.json() == []
    mock_execute.assert_called_once()

def test_list_presets_with_data(client: TestClient, mock_supabase_client_fixture):
    _, mock_execute = mock_supabase_client_fixture
    presets_data = [create_sample_preset_data(USER_ID_1, "1"), create_sample_preset_data(USER_ID_2, "2")]
    # Ensure UUIDs and datetimes are serialized as strings for the mock response, as they would be in JSON
    mock_response_data = [
        {**item,
         "preset_id": str(item["preset_id"]),
         "created_by": str(item["created_by"])
        } for item in presets_data
    ]
    mock_execute.return_value = MockSupabaseResponse(data=mock_response_data)

    response = client.get("/api/presets?skip=0&limit=10")
    assert response.status_code == 200
    data = response.json()
    assert len(data) == 2
    assert data[0]["preset_name"] == presets_data[0]["preset_name"]
    mock_execute.assert_called_once()


def test_get_preset_by_id_success(client: TestClient, mock_supabase_client_fixture):
    _, mock_execute = mock_supabase_client_fixture
    preset = create_sample_preset_data(USER_ID_1)
    mock_db_response_data = {**preset, "preset_id": str(preset["preset_id"]), "created_by": str(preset["created_by"])}
    mock_execute.return_value = MockSupabaseResponse(data=[mock_db_response_data])

    response = client.get(f"/api/presets/{preset['preset_id']}")
    assert response.status_code == 200
    data = response.json()
    assert data["preset_id"] == str(preset["preset_id"])
    mock_execute.assert_called_once()

def test_get_preset_by_name_success(client: TestClient, mock_supabase_client_fixture):
    _, mock_execute = mock_supabase_client_fixture
    preset = create_sample_preset_data(USER_ID_1, "ByNameTest")
    mock_db_response_data = {**preset, "preset_id": str(preset["preset_id"]), "created_by": str(preset["created_by"])}
    mock_execute.return_value = MockSupabaseResponse(data=[mock_db_response_data])

    response = client.get(f"/api/presets/{preset['preset_name']}")
    assert response.status_code == 200
    data = response.json()
    assert data["preset_name"] == preset["preset_name"]
    mock_execute.assert_called_once()

def test_get_preset_not_found(client: TestClient, mock_supabase_client_fixture):
    _, mock_execute = mock_supabase_client_fixture
    mock_execute.return_value = MockSupabaseResponse(data=[]) # Simulate not found

    response = client.get(f"/api/presets/{uuid.uuid4()}") # Random ID
    assert response.status_code == 404
    mock_execute.assert_called_once()

def test_update_preset_success_by_id(client: TestClient, mock_supabase_client_fixture):
    _, mock_execute = mock_supabase_client_fixture
    preset_id = uuid.uuid4()
    original_preset = create_sample_preset_data(USER_ID_1)
    original_preset["preset_id"] = preset_id

    update_payload = {"description": "Updated Description", "tags": ["updated"]}

    # Mock DB response for update - returns the updated item
    updated_db_data = {
        **original_preset,
        "description": update_payload["description"],
        "tags": update_payload["tags"],
        "updated_at": datetime.now(timezone.utc).isoformat(),
        "preset_id": str(preset_id), # Ensure string for comparison
        "created_by": str(USER_ID_1)
    }
    mock_execute.return_value = MockSupabaseResponse(data=[updated_db_data])

    response = client.put(f"/api/presets/{preset_id}", json=update_payload)

    assert response.status_code == 200
    data = response.json()
    assert data["description"] == update_payload["description"]
    assert data["tags"] == update_payload["tags"]
    assert data["preset_id"] == str(preset_id)
    mock_execute.assert_called_once()


def test_update_preset_not_found(client: TestClient, mock_supabase_client_fixture):
    _, mock_execute = mock_supabase_client_fixture
    mock_execute.return_value = MockSupabaseResponse(data=[]) # Simulate not found or RLS denial

    update_payload = {"description": "Update non-existent"}
    response = client.put(f"/api/presets/{uuid.uuid4()}", json=update_payload)
    assert response.status_code == 404 # As per current API logic for no data returned
    mock_execute.assert_called_once()

def test_update_preset_empty_payload(client: TestClient):
    response = client.put(f"/api/presets/{uuid.uuid4()}", json={})
    assert response.status_code == 400 # No fields to update

# Conceptual RLS test for update: If created_by was different and RLS enforced,
# the update would effectively not find the row for that user, leading to a 404.
# Our mock for `test_update_preset_not_found` already covers this behavior
# by returning an empty list from the mocked `execute`.

def test_delete_preset_success_by_id(client: TestClient, mock_supabase_client_fixture):
    _, mock_execute = mock_supabase_client_fixture
    preset_id = uuid.uuid4()
    # Mock that delete operation found and "deleted" a row
    mock_execute.return_value = MockSupabaseResponse(data=[{"preset_id": str(preset_id)}])

    response = client.delete(f"/api/presets/{preset_id}")
    assert response.status_code == 204
    mock_execute.assert_called_once()

def test_delete_preset_not_found(client: TestClient, mock_supabase_client_fixture):
    _, mock_execute = mock_supabase_client_fixture
    mock_execute.return_value = MockSupabaseResponse(data=[]) # Simulate not found or RLS denial

    response = client.delete(f"/api/presets/{uuid.uuid4()}")
    assert response.status_code == 404 # As per current API logic
    mock_execute.assert_called_once()

# Conceptual RLS test for delete: Similar to update, a 404 is expected if RLS prevented action.
# `test_delete_preset_not_found` covers this.

def test_get_preset_invalid_uuid_format(client: TestClient):
    # The route uses Union[UUID, str]. If it's not a valid UUID, it's treated as a name.
    # If it's syntactically invalid FOR A UUID but could be a name, it will proceed to query by name.
    # True UUID validation error (422) from FastAPI path converter happens if the type hint is just UUID
    # and an invalid UUID string is provided.
    # Given current Union[UUID, str], a truly "invalid format" test for UUID that results in 422
    # at path conversion level is not straightforward unless the string is also problematic for path parsing.
    # For this test, we'll assume an ID that's not a UUID and not found as a name.
    _, mock_execute = mock_supabase_client_fixture # Need this to avoid errors if it tries to call
    mock_execute.return_value = MockSupabaseResponse(data=[])

    response = client.get("/api/presets/this-is-not-a-uuid-and-not-a-name")
    assert response.status_code == 404 # Will be treated as a name, and not found.
    mock_execute.assert_called_once() # Verifies it went to the DB
```
